l_hip_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
l_hip_roll:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
l_hip_yaw:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
l_knee_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
l_ankle_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
l_ankle_roll:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10

r_hip_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
r_hip_roll:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
r_hip_yaw:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
r_knee_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
r_ankle_pitch:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10
r_ankle_roll:
  position_d_gain: 400
  position_i_gain: 0
  position_p_gain: 1700
  feedforward_1st_gain: 500
  return_delay_time: 10

head_pitch:
  position_p_gain: 850
  return_delay_time: 10
  max_position_limit: 3075
  min_position_limit: 1024
head_yaw:
  position_p_gain: 850
  return_delay_time: 10
  max_position_limit: 3075
  min_position_limit: 1024
  
waist_pitch:
  position_p_gain: 850
  return_delay_time: 10
waist_yaw:
  position_p_gain: 850
  return_delay_time: 10
  

l_shoulder_pitch:
  position_p_gain: 850
  return_delay_time: 10 
l_shoulder_roll:
  position_p_gain: 850
  return_delay_time: 10
l_elbow_pitch:
  position_p_gain: 850
  return_delay_time: 10
  
r_shoulder_pitch:
  position_p_gain: 850
  return_delay_time: 10 
r_shoulder_roll:
  position_p_gain: 850
  return_delay_time: 10
r_elbow_pitch:
  position_p_gain: 850
  return_delay_time: 10




