offset:
  l_hip_pitch: 0.0
  l_hip_roll: 0.0
  l_hip_yaw: 0.0
  
  l_knee_pitch: 0.0
  l_ankle_pitch: 0.0
  l_ankle_pitch: 0.0
 
  r_hip_pitch: 0.0
  r_hip_roll: 0.0
  r_hip_yaw: 0.0
  
  r_knee_pitch: 0.0
  r_ankle_pitch: 0.0
  r_ankle_pitch: 0.0
  
  waist_yaw: 0.0 
  waist_pitch: 0.0

#  head_yaw: 0.0 
  head_pitch: 0.0

 
init_pose_for_offset_tuner:
  l_hip_pitch: 0.0
  l_hip_roll: 0.0
  l_hip_yaw: 0.0
  
  l_knee_pitch: 0.0
  l_ankle_pitch: 0.0
  l_ankle_pitch: 0.0
  
  r_hip_pitch: 0.0
  r_hip_roll: 0.0
  r_hip_yaw: 0.0
  
  r_knee_pitch: 0.0
  r_ankle_pitch: 0.0
  r_ankle_pitch: 0.0
  
  waist_yaw: 0.0 
  waist_pitch: 0.0

#  head_yaw: 0.0 
  head_pitch: 0.0



